# Set environment variables
# exec $HOME/.config/sway/scripts/session.sh

# Policykit
exec env QT_SCALE_FACTOR=1.5 /usr/libexec/lxqt-policykit-agent

# Start kanshi
exec_always kanshi

# Start applets
exec nm-applet
exec blueman-applet

# Sway idle
exec LT="$lock_timeout" ST="$screen_timeout" LT=${LT:-300} ST=${ST:-60} && \
    swayidle -w \
        timeout $LT 'swaylock -f -C $HOME/.config/sway/swaylock/config' \
        timeout $((LT + ST)) 'swaymsg "output * power off"' \
                      resume 'swaymsg "output * power on"'  \
        timeout $ST 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power off"' \
             resume 'pgrep -xu "$USER" swaylock >/dev/null && swaymsg "output * power on"'  \
        before-sleep 'swaylock -f' \
        lock 'swaylock -f' \
        unlock 'pkill -xu "$USER" -SIGUSR1 swaylock'
