# Set kanshi
exec_always kanshi

# Set wallpaper
set $wallpaper /$HOME/Pictures/wallpapers/art/wallhaven-vq75j8.jpg
output * bg $wallpaper fill

# Cliphist
#exec wl-paste --type text --watch cliphist store
#exec wl-paste --type image --watch cliphist store
