# Set inner/outer gaps
default_border pixel 2

# Default font
font pango:Noto Sans Bold 13

# class border bg text indicator child_border
client.focused #718096 #404552 #e0e0e0 #8f9eb4 #718096

# Start waybar
bar {
  swaybar_command waybar
}

# GTK / Cursor theme variables
set $cursor_theme Adwaita
set $cursor_size 32
seat seat0 xcursor_theme $cursor_theme $cursor_size
set $icon_theme Numix
set $gtk_theme adw-gtk3-dark
set $color_scheme prefer-dark

# GTK theme settings
exec_always {
    gsettings set org.gnome.desktop.interface cursor-theme $cursor_theme
    gsettings set org.gnome.desktop.interface cursor-size $cursor_size
    gsettings set org.gnome.desktop.interface icon-theme $icon_theme
    gsettings set org.gnome.desktop.interface gtk-theme $gtk_theme
    gsettings set org.gnome.desktop.interface color-scheme $color_scheme
}
