# Set inner/outer gaps
default_border pixel 2

# Default font
font pango:Noto Sans Mono 13

# class border bg text indicator child_border
client.focused #718096 #404552 #e0e0e0 #8f9eb4 #718096

# Start waybar
bar {
  swaybar_command waybar
}

# Set wallpaper
set $wallpaper $HOME/Pictures/wallpapers/art/wallhaven-vq75j8.jpg
output * bg $wallpaper fill

# GTK / Cursor theme variables
set $cursor_theme Adwaita
set $cursor_size 32
seat seat0 xcursor_theme $cursor_theme $cursor_size

set $icon_theme Numix-Circle
set $gtk_theme adw-gtk3-dark
set $color_scheme prefer-dark

set $text_scaling_factor 1.25
set $font_name "Noto Sans 11"
set $monospace_font_name "Noto Sans Mono 11"
set $document_font_name "Noto Sans 11"

set $font_antialiasing rgba
set $font_rgba_order rgb

# GTK theme settings
exec {
    gsettings set org.gnome.desktop.interface cursor-theme $cursor_theme
    gsettings set org.gnome.desktop.interface cursor-size $cursor_size

    gsettings set org.gnome.desktop.interface icon-theme $icon_theme
    gsettings set org.gnome.desktop.interface gtk-theme $gtk_theme
    gsettings set org.gnome.desktop.interface color-scheme $color_scheme

    gsettings set org.gnome.desktop.interface text-scaling-factor $text_scaling_factor

    gsettings set org.gnome.desktop.interface font-name $font_name
    gsettings set org.gnome.desktop.interface monospace-font-name $monospace_font_name
    gsettings set org.gnome.desktop.interface document-font-name $document_font_name

    gsettings set org.gnome.desktop.interface font-antialiasing $font_antialiasing
    gsettings set org.gnome.desktop.interface font-rgba-order $font_rgba_order
}
